### ISSUE TITLE
Turn Geant4 multithreading on

### ISSUE THREAD

**Issue by DraTeots** [conda-forge/geant4-feedstock#13]
Would be good to have multi threaded variant

**Comment by drbenmorgan** [comment]
I'd be interested in this too. To resolve the issue noted in #2, Geant4 can be built with the `global-dynamic` TLS model using the `GEANT4_BUILD_TLS_MODEL` cmake argument (so `-DGEANT4_BUILD_TLS_MODEL=global-dynamic`)

**Comment by chrisburr** [comment]
Done in #15
