### ISSUE TITLE
Version updates for latest 10.7 release

### ISSUE THREAD

**Issue by drbenmorgan** [conda-forge/geant4-feedstock#18]
Geant4 10.7 was released today, and I already see a bot has picked this up in #17 😄. It's got the version bump right, but to help with updates to dependencies and data libraries, the changed requirements for the new version are:

- clhep =2.4.4.0
- geant4-data-emlow =7.13
- geant4-data-ensdfstate =2.3
- geant4-data-particlexs =3.1
- geant4-data-photonevaporation =5.7
- geant4-data-pii =1.3
- geant4-data-radioactivedecay =5.6
- geant4-data-realsurface =2.2

The feedstocks from those look already updated, so should be o.k. The only other options to explore adding to the recipe for 10.7 would be `GEANT4_USE_PYTHON`, which builds/installs Python bindings for Geant4. A few of caveats here:

- It needs Python 3 or newer *and* Boost.Python (tested with 1.73, but earlier should be fine)
- The default install path is `CMAKE_INSTALL_PREFIX/<libdir>/python3.Y/site-packages` but can be changed using the `CMAKE_INSTALL_PYTHON_DIR` CMake variable.
- A relative `INSTALL_RPATH` is set on the installed modules from their location to the Geant4 C++ libraries.

I'm not sure if those would play nice with Conda or not, so it's not required to add, and equally happy to have feedback on improving this part of the build/install!

I'm also happy to make the PR, but with the bot one there already I wasn't sure of policy/proceedure here. Let me know and can work to get at least the version bump done!

**Comment by Tobias-Fischer** [comment]
We package version 11 now - I think this can be closed.
