### ISSUE TITLE
Support for macos 11.6.x (but in general Big Sur)

### ISSUE THREAD

**Issue by HealthyPear** [conda-forge/geant4-feedstock#35]
#### Related issues

- #32 
- #19

#### (Apparent) Reason

For what concerns **Qt support,** it seems that macos 11 started to be supported from Qt6

- 6.1 reached End-of-Life as of September 2021
- 6.2 LTS supports macos with the following specs

<img width="910" alt="image" src="https://user-images.githubusercontent.com/17836610/170231890-289dcf35-889d-4ebd-82ec-de984115b67f.png">

Unfortunately I cannot seem to find a Qt6 conda package (Il'' open an issue in the corresponding feedstock)

**OpenGL support** was deprecated in macOS 10.14...

**Comment by Tobias-Fischer** [comment]
I'm not sure I understand your issue. Could you please be more precise what is/isn't working?

**Comment by HealthyPear** [comment]
Basically I am trying to run exampleB1, it runs, but I cannot see any GUI.

I investigated a bit, and I noticed that the Qt package shipped with the environment create with `conda create --name test-g4-tutuorial geant4 compilers cmake make` is 5.12, which supported macos up to 10.15, whereas I have 11.6.6.

At least I think this is the problem. (at the bottom of #19 I wrote what I tried - meanwhile I also opened a [thread](https://geant4-forum.web.cern.ch/t/macos-11-6-6-conda-installation-gui/7933/4) on Geant4 forum, but there not many people uses conda...)

**Comment by HealthyPear** [comment]
(on Ubuntu 20.04 LTS it works, but there it's using OpenGL)

**Comment by ckoern** [comment]
Have you tried `export QT_MAC_WANTS_LAYER=1` before running you Geant4 application?
With that, I am able to run my simulations on an M1 Mac with Big Sur

**Comment by HealthyPear** [comment]
Thank you @ckoern, what you suggested fixed my problem!

@Tobias-Fischer maybe this also fixes this issue?

**Comment by HealthyPear** [comment]
I think this "trick" should be reported at least in the README (unless it was a problem in the setups of me and @ckoern )

**Comment by ckoern** [comment]
Glad to hear, that it worked for you!
I think, this is a Qt 5.12 specific issue as Big Sur is not officially supported there but will not be needed for 5.15. 
You should also expect to see some artefacts in the visualization but no real showstopper.
As Qt 5.15 seems very close to be integrated into the qt-feedstock, that workaround should not be needed for too long so I don't know, if any readme notice is necessary anymore. And 5.15 will also bring the Qt3D viewer as a visualization option, so it is not needed anymore to use the OpenGL drivers (which have been deprecated by apple), so this will hopefully be a great improvement for Geant4 on osx.

**Comment by Tobias-Fischer** [comment]
We've got qt 5.15 now - is this still an issue?

**Comment by HealthyPear** [comment]
Sorry for the delay of some months!

I recently re-installed Geant 4 11.0.3 and it comes with
qt-main                   5.15.6               haeff654_6    conda-forge 

and e.g. the interactive visualization of example B1 works fine - closing issue!
