### ISSUE TITLE
face this missinng library when i'm going to make the example B1 Geant4

### ISSUE THREAD

**Issue by MFarooq786** [conda-forge/geant4-feedstock#8]
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libSM.so: undefined reference to `uuid_generate@UUID_1.0'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libSM.so: undefined reference to `uuid_unparse_lower@UUID_1.0'
collect2: error: ld returned 1 exit status
CMakeFiles/exampleB1.dir/build.make:294: recipe for target 'exampleB1' failed
make[2]: *** [exampleB1] Error 1
CMakeFiles/Makefile2:99: recipe for target 'CMakeFiles/exampleB1.dir/all' failed
make[1]: *** [CMakeFiles/exampleB1.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by chrisburr** [comment]
This is now fixed:

```bash
conda create --name test-g4-tutuorial geant4 compilers cmake make
conda activate test-g4-tutuorial

mkdir test-g4-tutuorial
cd test-g4-tutuorial
cmake $CONDA_PREFIX/share/Geant4-10.6.2/examples/basic/B1
make -j4
./exampleB1 run2.mac
```
